apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-probes
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: kuzhamuratov/online_inference:v2
      name: fastapi-ml
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 5
      livenessProbe:
            httpGet:
                path: /health
                port: 8000            
            initialDelaySeconds: 30
            periodSeconds: 10