apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-resources
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: kuzhamuratov/online_inference:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
            memory: "1Gi"
            cpu: 1
        limits:
            memory: "2Gi"
            cpu: 1.5