model: GradientBoosting
params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
train_test_split:
    shuffle: True
    test_size: 0.2
    random_state: 42
inference: False
debug: True
files:
    model_path: '${hydra:runtime.cwd}/outputs/gradient_boosting.pkl'
    data_path: '${hydra:runtime.cwd}/ml_project/data/heart_cleveland_upload.csv'
    stats_path: '${hydra:runtime.cwd}/outputs/column_mean_std_stats.sav'
    results_path: '${hydra:runtime.cwd}/outputs/prediction.csv'
    log_path: '${hydra:runtime.cwd}/outputs/file.log'