model: GradientBoosting
params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
train_test_split:
    shuffle: True
    test_size: 0.2
    random_state: 42
model_path: './outputs/gradient_boosting.pkl'